apiVersion: v1
kind: Service
metadata:
  name: php-todo-api-service
  namespace: php-todo-app
  labels:
    app: php-todo-api
spec:
  type: NodePort
  selector:
    app: php-todo-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
